name: hackerearth_api
description: Simple and easy-to-use Dart wrapper for HackerEarth API which provides endpoints for compiling and running code in several languages.
version: 1.0.0
homepage: https://github.com/piedcipher/hackerearth-api
author: Tirth Patel <pateltirth454@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  demoji: ^1.0.1

dev_dependencies:
  test: ^1.9.3
