name: hackerearth_api
description: Simple and easy-to-use Dart wrapper for HackerEarth API which provides endpoints for compiling and running code in several languages.
version: 1.0.0
homepage: https://github.com/piedcipher/hackerearth-api
author: Tirth Patel <pateltirth454@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http:
  demoji:

dev_dependencies:
  test:
